# Generated by Django 6.0.3 on 2026-03-29 19:07

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('type_color', models.CharField(blank=True, max_length=50)),
                ('registrations', models.IntegerField(default=0)),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('dept', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('is_open', models.BooleanField(default=True)),
                ('image_color', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
            ],
        ),
        migrations.CreateModel(
            name='HostEventRequest',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('event_title', models.CharField(max_length=255)),
                ('organizer_details', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('participants_count', models.IntegerField()),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations_list', to='events.event')),
            ],
        ),
    ]
