# Generated by Django 5.2.10 on 2026-01-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('type_color', models.CharField(blank=True, max_length=50)),
                ('registrations', models.IntegerField(default=0)),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('dept', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('is_open', models.BooleanField(default=True)),
                ('image_color', models.CharField(blank=True, max_length=50)),
                ('image', models.URLField(blank=True)),
            ],
        ),
    ]
