# Generated by Django 6.0.3 on 2026-04-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_id_alter_eventregistration_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='author_image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='author_member_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
