# Generated by Django 6.0.3 on 2026-04-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_add_author_image_url_and_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='author_member_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
