# Generated by Django 6.0.3 on 2026-03-29 19:07

from django.conf import settings
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                (
                    'id',
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
                    if settings.DATABASES['default']['ENGINE'] == 'django.db.backends.sqlite3'
                    else django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('member_type', models.CharField(choices=[('learner', 'Learner'), ('gig_worker', 'Gig Worker'), ('mentor', 'Mentor')], default='learner', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profile_details', models.TextField(blank=True)),
                ('expertise_skills', models.CharField(blank=True, max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
