"""
Django settings for cdls_ignite_backend project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv  # type: ignore
import dj_database_url  # type: ignore

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
load_dotenv(BASE_DIR.parent / '.env')




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-2+6qkvg!gd^tr9yi5wq39$7o6xb$ni^rxgau6op#40fdu!79h2')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') if os.environ.get('ALLOWED_HOSTS') else ['*']

# Ensure absolute URIs are constructed with 'https' behind reverse proxies (like Render)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

MONGO_URI = os.environ.get('MONGO_URI')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites', # Required by allauth

    # Third-party apps
    'cloudinary',
    'cloudinary_storage',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'dj_rest_auth',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    # Local apps
    'accounts',
    'core',
    'events',
    'members',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # Added CORS middleware
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware', # Added Allauth middleware
]

ROOT_URLCONF = 'cdls_ignite_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cdls_ignite_backend.wsgi.application'


# ── Database ─────────────────────────────────────────────────────────────────
# Use USE_LOCAL_DB=True in .env to switch to SQLite (e.g. when VPN blocks Atlas)
# Production (Render) always uses MongoDB Atlas via MONGO_URI.

_use_local = os.environ.get('USE_LOCAL_DB', 'False') == 'True'
_mongo_uri  = os.environ.get('MONGO_URI')

if _use_local or not _mongo_uri:
    # ── Local: SQLite (no network needed) ────────────────────────────────────
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # ── Production / Atlas: MongoDB ──────────────────────────────────────────
    DATABASES = {
        'default': {
            'ENGINE': 'django_mongodb_backend',
            'NAME': 'cdls_ignite',
            'HOST': _mongo_uri,
        }
    }

# Update database configuration from environment variable (if available)
# db_from_env = dj_database_url.config(conn_max_age=600)
# DATABASES['default'].update(db_from_env)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

CSRF_TRUSTED_ORIGINS = ['https://*.onrender.com']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# Use MongoDB's ObjectId for primary keys in production; BigAutoField for SQLite locally
if _use_local or not _mongo_uri:
    DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
else:
    DEFAULT_AUTO_FIELD = 'django_mongodb_backend.fields.ObjectIdAutoField'
    # Silence the AutoField system check for third-party apps (auth, allauth, contenttypes).
    SILENCED_SYSTEM_CHECKS = ['django_mongodb_backend.W004', 'mongodb.E001', 'mongodb.W001']
    # Disable Django's built-in migrations for apps that use AutoField pk.
    # Forces syncdb which respects DEFAULT_AUTO_FIELD=ObjectIdAutoField.
    # This prevents the "Model instances without primary key value are unhashable"
    # error in post_migrate signals (create_permissions) on MongoDB.
    MIGRATION_MODULES = {
        'contenttypes': None,
        'auth': None,
        'admin': None,
        'sessions': None,
        'sites': None,
        'account': None,
        'socialaccount': None,
        'authtoken': None,
    }

# ── Media / File Storage ──────────────────────────────────────────────────────
# Use Cloudinary in production (when CLOUDINARY_URL env var is set on Render).
# Falls back to local disk (media/) for local development.
_cloudinary_url = os.environ.get('CLOUDINARY_URL')

if _cloudinary_url:
    import cloudinary  # type: ignore[import]
    cloudinary.config(cloudinary_url=_cloudinary_url)
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    # MEDIA_URL is not used when Cloudinary handles storage,
    # but keep it defined so existing code that references it doesn't break.
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
else:
    # Local development: serve from the local media/ directory.
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Custom User Model
AUTH_USER_MODEL = 'accounts.CustomUser'

# CORS
CORS_ALLOW_ALL_ORIGINS = True # For development only

# Email backend — required by allauth even when verification is 'optional'.
# Using the console backend here so no SMTP server is needed.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# DRF Configuration — token-only authentication (no session cookies)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
}

# dj-rest-auth — disable session login so django_login() is never called.
# We only use DRF Token auth, so sessions are not needed and would cause
# errors on MongoDB (no django_session table).
REST_AUTH = {
    'SESSION_LOGIN': False,
}

SITE_ID = 1

# Allauth Configuration (Django-allauth v65+)
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']  # email is required
ACCOUNT_LOGIN_METHODS = {'email'}          # login via email only
ACCOUNT_EMAIL_VERIFICATION = 'optional'
