# Generated by Django 5.2.10 on 2026-01-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_interestexpression'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='interestexpression',
            name='category',
            field=models.CharField(choices=[('volunteer', 'Volunteer'), ('coworker', 'Co-worker'), ('startup', 'Startup'), ('general', 'General Interest')], default='general', max_length=20),
        ),
    ]
